# Use new travis-ci infrastructure
sudo: false

language: python

os:
  - linux
#  - osx

python:
  - "2.7"
  - "3.5"
  - "3.6"
#  - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0

before_install:
   # install bedtools from source
   # TODO use always last avaible released or fixed release?
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.25.0/bedtools-2.25.0.tar.gz -O
  bedtools.tar.gz
  - tar -zxvf bedtools.tar.gz
  - cd bedtools
  - make
  # install other requirements
  - cd ..
  - pip install -r requirements.txt -r test_requirements.txt

install:
  - python setup.py install

script:
    - nosetests --with-coverage --cover-package=dorina

after_success:
    - coveralls

notifications:
    email: false
