# Use new travis-ci infrastructure
sudo: false

language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.27.1/bedtools-2.27.1.tar.gz
  - tar -zxvf bedtools-2.27.1.tar.gz
  - cd bedtools2
  - make

install:
  - cd dieterich-lab/dorina
  - pip install -r requirements.txt -r test_requirements.txt
  - python setup.py install

script:
    - nosetests --with-coverage --cover-package=dorina

after_success:
    - coveralls

notifications:
    email: false
