language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0

cache: pip

jobs:
  include:
    - stage: unit
      script: coverage run -m unittest discover tests/unit

install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nosetests

after_success: coveralls