sudo: true

language: python

os:
  - linux

python:
#  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install bedtools
  - pip install -r requirements.txt -r test_requirements.txt

install:

  - python setup.py install

script:
    - nosetests --with-coverage --cover-package=dorina

after_success:
    - coveralls

notifications:
    email: false
