# Use new travis-ci infrastructure
sudo: false

language: python

os:
  - linux
#  - osx

python:
  - "2.7"
  - "3.5"
#  - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0

install:
  - sudo apt-get update
  - apt-get install bedtools
  - pip install -r requirements.txt -r test_requirements.txt
  - python setup.py install

script:
    - nosetests --with-coverage --cover-package=dorina

after_success:
    - coveralls

notifications:
    email: false
