#!/usr/bin/env python
# vim: set fileencoding=utf-8 :

import sys
import logging
import argparse
from dorina.config import load_config, set_config
from dorina import utils

def main():
    parser = argparse.ArgumentParser(description="Run doRiNA from the command line")
    parser.add_argument('-d', '--debug', dest='debug',
                        action='store_true', default=False,
                        help="print debugging information to stderr")
    parser.add_argument('-v', '--verbose', dest='verbose',
                        action='store_true', default=False,
                        help="print verbose status information to stderr")
    parser.add_argument('--list-genomes', dest='list_genomes',
                        action='store_true', default=False,
                        help="print a list of available genomes and exit")
    parser.add_argument('--list-regulators', dest='list_regulators',
                        action='store_true', default=False,
                        help="print a list of available regulators and exit")

    options = parser.parse_args()

    setup_logging(options)

    load_config(options)
    set_config(options)

    if options.list_genomes:
        list_genomes()
        sys.exit(0)

    if options.list_regulators:
        list_regulators()
        sys.exit(0)


    logging.error("This program doesn't do anything yet")
    sys.exit(1)


def setup_logging(options):
    """Set up the logging output"""
    if options.debug:
        log_level = logging.DEBUG
    elif options.verbose:
        log_level = logging.INFO
    else:
        log_level = logging.WARNING

    logging.basicConfig(format="%(levelname)s: %(message)s",
                        level=log_level)


def list_genomes():
    """List all available genomes"""
    genomes = utils.get_genomes()
    print "Available genomes:"
    print "------------------"
    for clade, clade_dict in genomes.items():
        print "%s" % clade
        for species, species_dict in clade_dict.items():
            print "\t%s" % species
            for assembly, assembly_dict in species_dict.items():
                print "\t\t%s" % assembly
                gffs = assembly_dict.items()
                gffs.sort(key=lambda x: x[0])
                for gff in gffs:
                    print "\t\t\t%s: %s" % gff


def list_regulators():
    """List all available regulators"""
    regulators = utils.get_regulators()
    print "Available regulators:"
    print "---------------------"
    for regulator, regulator_dict in regulators.items():
        print "%s" % regulator
        items = regulator_dict.items()
        items.sort(key=lambda x: x[0])
        for name, data in items:
            print "\t%s" % name
            print "\t\t%s" % data['summary']

if __name__ == "__main__":
    main()
